import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

/// Production-oriented authentication service.
///
/// Security rules:
/// - Never store passwords locally.
/// - Never log passwords.
/// - Never hardcode secrets; Firebase config is provided by `flutterfire configure`.
class AuthService {
  AuthService({FirebaseAuth? firebaseAuth}) : _auth = firebaseAuth ?? FirebaseAuth.instance;

  final FirebaseAuth _auth;

  Stream<User?> authStateChanges() => _auth.authStateChanges();

  User? get currentUser => _auth.currentUser;

  Future<void> signUpWithEmailAndPassword({
    required String email,
    required String password,
  }) async {
    await _auth.createUserWithEmailAndPassword(email: email, password: password);
  }

  Future<void> signInWithEmailAndPassword({
    required String email,
    required String password,
  }) async {
    await _auth.signInWithEmailAndPassword(email: email, password: password);
  }

  Future<void> sendPasswordResetEmail({required String email}) async {
    await _auth.sendPasswordResetEmail(email: email);
  }

  Future<void> logout() async {
    // Firebase sign out first to prevent stale auth state.
    await _auth.signOut();

    // Google sign-in state is not secret, but we still sign out to clean up sessions.
    await GoogleSignIn().signOut();
  }

  /// Google Sign-In.
  ///
  /// Notes:
  /// - This assumes Google OAuth is enabled in your Firebase project.
  /// - Configuration is provided at runtime by Firebase config generated by `flutterfire configure`.
  Future<void> signInWithGoogle() async {
    final googleUser = await GoogleSignIn().signIn();
    if (googleUser == null) return; // User cancelled.

    final googleAuth = await googleUser.authentication;
    final accessToken = googleAuth.accessToken;
    final idToken = googleAuth.idToken;

    if (accessToken == null || idToken == null) {
      throw FirebaseAuthException(
        code: 'google_auth_failed',
        message: 'Missing Google OAuth tokens.',
      );
    }


    final credential = GoogleAuthProvider.credential(
      accessToken: accessToken,
      idToken: idToken,
    );

    await _auth.signInWithCredential(credential);
  }
}

